name: CI MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "./wine-quality.csv"
  TARGET_VAR: "quality"
  ALPHA: 0.5
  L1_RATIO: 0.5
  RANDOM_STATE: 42

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository untuk memastikan file tersedia
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Check Env Variables
      - name: Check Env
        run: |
          echo "CSV_URL: $CSV_URL"
          echo "Target Variable: $TARGET_VAR"

      # Install MLflow dan dependensi lainnya
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Pastikan repository telah diinisialisasi dengan Git
      - name: Ensure Git repository is initialized
        run: |
          git init
          git remote -v || git remote add origin git@github.com:hutomo20241446/Project.git
          git fetch --all
          git reset --hard origin/main

      # Jalankan MLflow project dari direktori saat ini (bukan `Project/`)
      - name: Run MLflow project
        run: |
          mlflow run . --env-manager=local
